mainline/alpine-perl/Dockerfile, mainline/alpine/Dockerfile, mainline/stretch-perl/Dockerfile, mainline/stretch/Dockerfile, stable/alpine-perl/Dockerfile, stable/alpine/Dockerfile, stable/stretch-perl/Dockerfile, stable/stretch/Dockerfile
- Runs the docker container as user 1001 (unpriveleged) and group 0
(root)
- Not to run as root
- Not to run as nginx but an arbitrary user id
- Facilitate kubernetes security context
=> Runs the docker container as user 1001 (unpriveleged) and group 0 (root)

mainline/alpine-perl/Dockerfile, mainline/alpine/Dockerfile, mainline/buster-perl/Dockerfile, mainline/buster/Dockerfile, stable/alpine-perl/Dockerfile, stable/alpine/Dockerfile, stable/buster-perl/Dockerfile, stable/buster/Dockerfile
Resolves: https://github.com/nginxinc/docker-nginx-unprivileged/issues/23
The alpine images fail to start because the `nginx` user has no access to `/var/cache/nginx`.
`-H` must be removed so that the directory is created when instantiating the user.
=> 23 - Change ownership of var/cache to nginx user

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml
As initially suggested in #102, this PR updates the GH actions workflow to sign all Docker images using the Docker Content Trust (DCT) as part of the build process.
=> Implement Docker Content Trust

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml
Add support for pushing NGINX Docker images to GitHub's Container Registry in addition to Docker's Container Registry.
=> Add support for GHCR

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml
Implement caching in the GH actions pipeline. TBD how much this will benefit/speed up the pipeline given the few layers on the images, but it's better to have around than not.
=> Implement caching in the GH actions pipeline

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml, README.md
Publish Docker images on Amazon ECR. Closes #111.
=> Add support for Amazon ECR

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml
This PR aims to:
a) Add distribution release/version tags to new Docker images (similarly to what was done in https://github.com/nginxinc/docker-nginx/commit/beac75efbd331ef54c5409c410fbb4832ba09a3d in the upstream Docker NGINX repo)
b) Simplify the GitHub actions workflows to avoid duplicating code when pushing new Docker images to the various registries supported by this image.
=> Add distribution release/version tags to Docker images

mainline/alpine-perl/Dockerfile, mainline/alpine-slim/Dockerfile, mainline/alpine/Dockerfile, mainline/debian-perl/Dockerfile, mainline/debian/Dockerfile, update.sh
Updating mainline to NGINX 1.25.3, which [includes this change](https://nginx.org/en/CHANGES):
> Changes with nginx 1.25.3                                        24 Oct 2023
>
>    *) Change: improved detection of misbehaving clients when using HTTP/2.
Also updates njs to 0.8.2, which is required for the NGINX change to build.
Related to #166
=> Update mainline NGINX to 1.25.3

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml, README.md
=> Add Quay to the list of registries to which pre-built images are pushed

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml, .github/workflows/scripts/delete-untagged-amazon-public-ecr-images.sh
Amazon Public ECR does not automatically cleanup untagged images, which means that over time it's very easy to accumulate a non-trivial amount of images that are fundamentally useless. Since ECR Public also happens to not support life-cycle policies (https://github.com/aws/containers-roadmap/issues/1268), the only automated way to delete untagged images involves using the CLI in an automated script. This PR adds such a script (based on https://github.com/zeek/zeek/blob/master/ci/public-ecr-cleanup.sh, with a few minor tweaks) and incorporates it to the GitHub actions CD pipeline.
=> Cleanup/remove untagged Amazon Public ECR images when new images are built

entrypoint/10-listen-on-ipv6-by-default.sh, entrypoint/15-local-resolvers.envsh, entrypoint/20-envsubst-on-templates.sh, entrypoint/30-tune-worker-processes.sh, entrypoint/docker-entrypoint.sh, mainline/alpine-slim/10-listen-on-ipv6-by-default.sh, mainline/alpine-slim/15-local-resolvers.envsh, mainline/alpine-slim/20-envsubst-on-templates.sh, mainline/alpine-slim/30-tune-worker-processes.sh, mainline/alpine-slim/docker-entrypoint.sh, mainline/debian/10-listen-on-ipv6-by-default.sh, mainline/debian/15-local-resolvers.envsh, mainline/debian/20-envsubst-on-templates.sh, mainline/debian/30-tune-worker-processes.sh, mainline/debian/docker-entrypoint.sh, stable/alpine-slim/10-listen-on-ipv6-by-default.sh, stable/alpine-slim/15-local-resolvers.envsh, stable/alpine-slim/20-envsubst-on-templates.sh, stable/alpine-slim/30-tune-worker-processes.sh, stable/alpine-slim/docker-entrypoint.sh, stable/debian/10-listen-on-ipv6-by-default.sh, stable/debian/15-local-resolvers.envsh, stable/debian/20-envsubst-on-templates.sh, stable/debian/30-tune-worker-processes.sh, stable/debian/docker-entrypoint.sh
This PR ports the latest updates made to the upstream https://github.com/nginxinc/docker-nginx image. It adds IPv6 support for local-resolvers substitution script, addresses an Alpine bug, and fixes some shell linter warnings.
=> Add IPv6 support for local-resolvers substitution script

mainline/alpine-perl/Dockerfile, mainline/alpine-slim/Dockerfile, mainline/alpine/Dockerfile, mainline/debian-perl/Dockerfile, mainline/debian/Dockerfile, update.sh
Update mainline NGINX to 1.25.4 and mainline NJS to 0.8.3.
=> Update mainline NGINX to 1.25.4

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml
=> Cleanup untagged images on the GitHub Container Registry

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml, .github/workflows/image-cleanup.yml
=> Split image cleanup job into its own workflow

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, .github/workflows/debian-mainline.yml, .github/workflows/debian-stable.yml, .github/workflows/image-cleanup.yml
=> Update GH Actions runner to Ubuntu 24.04

mainline/alpine-perl/Dockerfile, mainline/alpine-slim/Dockerfile, mainline/alpine/Dockerfile, mainline/debian-perl/Dockerfile, mainline/debian/Dockerfile, update.sh
Update mainline NGINX to 1.27.2 and mainline NJS to 0.8.6.
=> feat: Update mainline NGINX to 1.27.2

mainline/alpine-perl/Dockerfile, mainline/alpine-slim/Dockerfile, mainline/alpine/Dockerfile, mainline/debian-perl/Dockerfile, mainline/debian/Dockerfile, update.sh
Update mainline NGINX to 1.27.3 and mainline NJS to 0.8.7.
=> feat: Update mainline NGINX to 1.27.3

.github/workflows/alpine-mainline.yml, .github/workflows/alpine-stable.yml, mainline/alpine-perl/Dockerfile, mainline/alpine-slim/Dockerfile, mainline/alpine/Dockerfile, mainline/debian-perl/Dockerfile, mainline/debian/Dockerfile, stable/alpine-perl/Dockerfile, stable/alpine-slim/Dockerfile, stable/alpine/Dockerfile, stable/debian-perl/Dockerfile, stable/debian/Dockerfile, update.sh
Add support for `riscv64` on Alpine Linux and update NJS to 0.8.8
=> Add `riscv64` support on Alpine Linux

mainline/alpine-perl/Dockerfile, mainline/alpine-slim/Dockerfile, mainline/alpine/Dockerfile, mainline/debian-perl/Dockerfile, mainline/debian/Dockerfile, stable/alpine-perl/Dockerfile, stable/alpine-slim/Dockerfile, stable/alpine/Dockerfile, stable/debian-perl/Dockerfile, stable/debian/Dockerfile, update.sh
Update mainline NGINX to 1.27.4, stable NGINX to 1.26.3, and NJS to 0.8.9
=> feat: Update mainline NGINX to 1.27.4

.github/workflows/image-cleanup.yml, .github/workflows/scripts/delete-untagged-amazon-public-ecr-images.sh, README.md
As of right now, the image cleanup workflow runs weekly and promptly deletes any untagged images in AWS ECR and GHCR. This PR tweaks the workflow to only delete images that are over two years old. The frequency can be adjusted down the line if deemed necessary.
=> feat: Only delete images over 2y old in AWS and GHCR

Dockerfile-alpine-slim.template, SUPPORT.md, mainline/alpine-perl/Dockerfile, mainline/alpine-slim/Dockerfile, mainline/alpine/Dockerfile, mainline/debian-perl/Dockerfile, mainline/debian/Dockerfile, stable/alpine-perl/Dockerfile, stable/alpine-slim/Dockerfile, stable/alpine/Dockerfile, stable/debian-perl/Dockerfile, stable/debian/Dockerfile, update.sh
* Update mainline NGINX to 1.27.5
* Stable NGINX to 1.28.0, Alpine Linux to 3.21, and NJS to 0.8.10
* Replace `gettext-envsubst` workaround with `gettext-envsubst` package
=> feat: Update mainline NGINX to 1.27.5

Dockerfile-alpine-slim.template, Dockerfile-debian.template, README.md, mainline/alpine-slim/Dockerfile, mainline/debian/Dockerfile, stable/alpine-slim/Dockerfile, stable/debian/Dockerfile
Fixing issue #302 caused by nginx/pkg-oss#26 and subsequently #301 by modifying the sed replacement such that they match for the old and the new PID file path (/var/run/nginx.pid and /run/nginx.pid shall be changed to /tmp/nginx.pid)
- I get weird errors about `greadlink` and `gsed` that I don't know/have
=> docker files and templates: consider changed pid file path from NGINX 1.27.5

Dockerfile-debian.template, mainline/debian/Dockerfile, stable/debian/Dockerfile
This makes sure all keys are exported to a keyring archive, as opposed to only the first key.
Same as in https://github.com/nginx/docker-nginx/commit/0b49b8b12fd214b633114ac16d2dfd65d45ff160
=> fix: Pass GPG key ids as separate arguments when exporting.
